version: '3.9'

services:
  vector-centralized:
    image: timberio/vector:0.24.0-alpine
    command: ["--config", "/etc/vector/*.toml", "--watch-config"]
    volumes:
      - ./vector-centralized/:/etc/vector/
    container_name: vector-centralized
    restart: always

  log-generator-1:
    build:
      context: ./logger
      dockerfile: ./dockerfile
    restart: always
    container_name: log-generator-1
    environment:
      - RUST_LOG=trace
      - PORT=5000
      - HOST=0.0.0.0
    ports:
      - "5000:5000"
  
  log-generator-2:
    build:
      context: ./logger
      dockerfile: ./dockerfile
    restart: always
    container_name: log-generator-2
    environment:
      - RUST_LOG=trace
      - PORT=5000
      - HOST=0.0.0.0
    ports:
      - "5001:5000"

  log-generator-3:
    build:
      context: ./logger
      dockerfile: ./dockerfile
    restart: always
    container_name: log-generator-3
    environment:
      - RUST_LOG=trace
      - PORT=5000
      - HOST=0.0.0.0
    ports:
      - "5002:5000"

  log-scraper-1:
    build: 
      context: ./log_scraper
      dockerfile: ./dockerfile
    container_name: log-scrapper
    restart: always
    environment:
      - RUST_LOG=trace
      - API_PORT=5000
      - SCRAPE_INTERVAL=10
      - VECTOR_INSTANCE_IP=http://vector-centralized:8000
      - CONFIG_PATH=/etc/scraper/config.json
    volumes:
      - ./log_scraper/config.json:/etc/scraper/config.json

  # rustlogger-2:
  #   build:
  #     context: ./logger
  #     dockerfile: ./dockerfile
  #   restart: always
  #   container_name: rustlogger-2
  #   environment:
  #     - RUST_LOG=trace

  # rustlogger-3:
  #   build:
  #     context: ./logger
  #     dockerfile: ./dockerfile
  #   restart: always
  #   container_name: rustlogger-3
  #   environment:
  #     - RUST_LOG=trace

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true.
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  loki:
    image: grafana/loki:2.6.0
    container_name: loki
    ports:
      - "3100:3100"

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - TSTUNE_PROFILE=promscale
      - POSTGRES_USER=postgres

  promscale:
    image: timescale/promscale:latest
    container_name: promscale
    ports:
      - "9201:9201"
    restart: always
    environment:
      - PROMSCALE_DB_URI=postgres://postgres:postgres@timescaledb:5432/postgres?sslmode=allow