version: '3.9'

services:
  vector-centralized:
    image: timberio/vector:0.24.0-alpine
    command: ["--config", "/etc/vector/*.toml", "--watch-config"]
    volumes:
      - ./vector-centralized/:/etc/vector/
      - ~/tmp:/logs
    container_name: vector-centralized
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true.
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  loki:
    image: grafana/loki:2.6.0
    container_name: loki
    ports:
      - "3100:3100"

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - TSTUNE_PROFILE=promscale
      - POSTGRES_USER=postgres

  promscale:
    image: timescale/promscale:latest
    container_name: promscale
    ports:
      - "9201:9201"
    restart: always
    environment:
      - PROMSCALE_DB_URI=postgres://postgres:postgres@timescaledb:5432/postgres?sslmode=allow
