remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true

global:
  scrape_interval: "5s"
  evaluation_interval: "5s"

scrape_configs:
  - job_name: "vector"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "vector-aggregator:9598"