apiVersion: 1

datasources:
  - name: Prometheus (Timescaledb) - Vector playing
    uid: 1
    type: prometheus
    access: proxy
    url: http://promscale:9201
    jsonData:
      httpMethod: POST


  - name: Loki - Vector playing
    uid: 2
    type: loki
    access: proxy
    url: http://loki:3100
    default: true
