[package]
name = "file_watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.12"
reqwest = {version = "0.11.2", features = ["blocking"]}
env_logger = "0.9.1"
log = "0.4.17"
