{
 "title": "CPU dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Physical cpus",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{mode=\"physical_cpus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logical cpus",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{mode=\"logical_cpus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU seconds total 0",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{cpu=\"0\", mode!=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU seconds total 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{cpu=\"1\", mode!=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU seconds total 2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{cpu=\"2\", mode!=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU seconds total 3",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{cpu=\"3\", mode!=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU seconds total 1 - idle",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{cpu=\"1\", mode=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU seconds total 0 - idle",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{cpu=\"1\", mode=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU seconds total 2 - idle",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{cpu=\"2\", mode=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU seconds total 3 - idle",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "host_cpu_seconds_total{cpu=\"3\", mode=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}