[sources.logs]
type = "file"
include = [ "/logs/**/*.log" ]
read_from = "beginning"

[transforms.to_json]
type = "remap"
inputs = [ "logs" ]
source = """
. = parse_json!(.message)
"""

# Debug purposes
# [sinks.out]
# type = "console"
# inputs = ["to_json"]
# target = "stdout"
#     [sinks.out.encoding]
#     codec = "text"

[sinks.out_logs]
type = "loki"
inputs = ["to_json"]
endpoint = "http://loki:3100"
compression = "none"
    [sinks.out_logs.labels]
    ic_node = "{{ node_id }}"
    ic_subnet = "{{ subnet_id }}"
    [sinks.out_logs.encoding]
    codec = "json"
