[sources.logs]
type = "http"
address = "0.0.0.0:8000"
encoding = "text"
path = "/"
method = "POST"

[transforms.to_json_array]
type = "remap"
inputs = [ "logs" ]
source = """
. = parse_json!(.message)
"""

[transforms.to_json]
type = "remap"
inputs = [ "to_json_array" ]
source = """
. = parse_json!(.message)
"""
# Debug purposes
# [sinks.out]
# type = "console"
# inputs = ["to_json"]
# target = "stdout"
#     [sinks.out.encoding]
#     codec = "text"

[sinks.out_logs]
type = "loki"
inputs = ["to_json"]
endpoint = "http://loki:3100"
compression = "none"
    [sinks.out_logs.labels]
    ic_node = "{{ ic_node }}"
    ic_subnet = "{{ ic_subnet }}"
    dc = "{{ dc }}"
    ip = "{{ ip }}"
    [sinks.out_logs.encoding]
    codec = "json"